[versions]
kotlin = "2.2.21"
junit-jupiter = "6.0.1"
springdoc = "2.8.14"
micrometer = "1.16.1"
lombok = "1.18.42"
jakarta-json = "3.0.1"
okta = "3.0.7"
spring-dotenv = "4.0.0"
wiremock = "3.0.1"
blockhound = "1.0.15.RELEASE"
commons-math3 = "3.6.1"
spring-boot = "3.5.7"
reactor-kotlin-extensions = "1.3.0"
kotlinx-coroutines-reactor = "1.10.2"

[plugins]
jesperancinha-omni = { id = "org.jesperancinha.plugins.omni", version = "0.4.5" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version = "3.5.7" }
spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }
openapi-gradle-plugin = { id = "org.springdoc.openapi-gradle-plugin", version = "1.9.0" }

[libraries]
junit-jupiter-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit-jupiter" }
springdoc-openapi-starter-webflux-ui = { group = "org.springdoc", name = "springdoc-openapi-starter-webflux-ui", version.ref = "springdoc" }
springdoc-openapi-starter-common = { group = "org.springdoc", name = "springdoc-openapi-starter-common", version.ref = "springdoc" }
r2dbc-postgresql = { group = "io.r2dbc", name = "r2dbc-postgresql", version = "0.8.13.RELEASE" }
micrometer-registry-prometheus = { group = "io.micrometer", name = "micrometer-registry-prometheus", version.ref = "micrometer" }
micrometer-core = { group = "io.micrometer", name = "micrometer-core", version.ref = "micrometer" }
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
jakarta-json-bind-api = { group = "jakarta.json.bind", name = "jakarta.json.bind-api", version.ref = "jakarta-json" }
okta-spring-boot-starter = { group = "com.okta.spring", name = "okta-spring-boot-starter", version.ref = "okta" }
spring-dotenv = { group = "me.paulschwarz", name = "spring-dotenv", version.ref = "spring-dotenv" }
wiremock = { group = "com.github.tomakehurst", name = "wiremock", version.ref = "wiremock" }
blockhound-junit-platform = { group = "io.projectreactor.tools", name = "blockhound-junit-platform", version.ref = "blockhound" }
commons-math3 = { group = "org.apache.commons", name = "commons-math3", version.ref = "commons-math3" }
spring-boot-bom = { group = "org.springframework.boot", name ="spring-boot-starter-parent", version.ref = "spring-boot" }
reactor-kotlin-extensions = { group = "io.projectreactor.kotlin", name = "reactor-kotlin-extensions", version.ref = "reactor-kotlin-extensions" }
reactor-test = { group = "io.projectreactor", name = "reactor-test", version = "3.8.0" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-reactor = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-reactor", version.ref = "kotlinx-coroutines-reactor" }
